### PR TITLE
Add a note about the community sprint

### PR DESCRIPTION
**Pull request by hroncok**
This revers "removed zpetnovazebnik" and builds on top of it.

This reverts commit e455f5fe4e85afd3f9d3e43dd955a753272e3622.

### CODE REVIEW

**Comment by honzajavorek** [comment]
The same thing was on python.cz as well

**Comment by honzajavorek** [comment]
Check the CI pls, I’m on a phone

**Comment by hroncok** [comment]
Also, rebased, my master was old. Will check the CI and merge if it's green.

**Comment by hroncok** [comment]
OK, the PR CI was fine, but after merge, the push CI is red.

@encukou Could you help us?

**Comment by encukou** [comment]
The CI is flaky; I need to figure out why.

Deployment of pyvo.cz is still manual. I deployed it.

**Comment by hroncok** [comment]
Thank You.

**Pull request merged**
