### PR TITLE
Venue notes

### PR DESCRIPTION
**Pull request by encukou**
This makes it possible to attach venue notes (e.g. directions to get there)

Depends on https://github.com/pyvec/pyvodb/pull/5
To see the effect, some venues need to be in the data. [Beer Factory in Plzeň](https://github.com/pyvec/pyvo-data/blob/master/cities/plzen/venues/beer-factory.yaml) has some, but change the key name from `notes` to `note`. (We'll need to adjust the data anyway, to pull out stuff that's only relevant to one meetup.)

There is a refactoring step in the middle. Please leave any bikeshedding about that to some later commit. (I wrote the `fragments/` thing before I knew much about Jinja...)

### CODE REVIEW

**Comment by hroncok** [comment]
I don't except to review this properly until tmrw. But the change makes sense. Will there be a relevant data PR?

**Comment by encukou** [comment]
Tomorrow. :)

**Comment by encukou** [comment]
@hroncok I plan to merge the 3 PRs during the weekend, so they're in for Plzeň.
That's just FYI, there's no rush, having a review before merging is not critical.

**Comment by hroncok** [comment]
I plan to do this within this hour.

**Comment by hroncok** [comment]
First of all. Works great for Plzeň.

plzen

**Comment by hroncok** [comment]
Some older Prague one seems to work as well. 
praha

**Comment by encukou** [comment]
> Some older Prague one seems to work as well.

I don't think it really matters here. I'm even considering hiding the note for past events, what do you think?

**Pull request merged**
